### PR TITLE
Added options for URLScan results

### PR DESCRIPTION
**Pull request by jenetiks**
Added option for public and private URLScan's
see Issue #62 

## Description ##
Added option for users to choose public or private scans for URLScan.io

## Does this fix a known existing bug under Issues? ##
No fixes

## Type of Change ##
Please delete any options that **do not** apply here:
- [ ] New Feature

## Any further info related to the addition ##
Sorry, i got bored at work and figured I'd jimmy something up

### CODE REVIEW

**Review by TheresAFewConors — CHANGES_REQUESTED** [review]
I like the idea here, as far as the implementation goes I think it would be best to save the user option to a file and instead offer a toggle option for privacy, rather than ask on each request. 

Good addition here. It solves a couple of open issues too.

**Comment by jenetiks** [comment]
I can work on getting those changes in today and subs for review.

And thanks :)

**Comment by jenetiks** [comment]
Do you want a new PR for this?

**Comment by jenetiks** [comment]
Closed PR, new open #67

**Pull request closed without merging**
