### PR TITLE
Added options for URLScan results [New]

### PR DESCRIPTION
**Pull request by jenetiks**
## Description ##
Made desired changes to URLScan options: default = private and option to set to public in config file.

## Does this fix a known existing bug under Issues? ##
Nope

## Type of Change ##
Please delete any options that **do not** apply here:
- [ ] New Feature

## Any further info related to the addition ##
Can close old PR bc I'm a terd.

### CODE REVIEW

**Comment by TheresAFewConors** [comment]
Its looking good - would you be able to add an option to switch from public to private too without having to modify the .yaml file? A simple 1 for pub / 2 for priv would suffice I would think. 

After that I think this would be perfect for merging.

**Review by TheresAFewConors — CHANGES_REQUESTED** [review]
reviewed - requested toggle in cli to switch between pub and priv.

**Comment by jenetiks** [comment]
Sure can

**Comment by jenetiks** [comment]
Changes are up. Without modifying more of the app, I think we have to keep the prompt within the function itself. If you're okay with more modification, I can muck around to have it prompt once and only once.  But I think the small prompt on every scan is sufficient and not too cumbersome on users. Open to ideas though :D

**Review by TheresAFewConors — APPROVED** [review]
Looks good to me, functions well too. 

It would be nice in future to have it default to 'private', and then provide the option to toggle to 'public' if required. 

Currently the option stored in the config.yaml is redundant if the user is selecting on each scan anyway. I edited the PR to remove this part, and instead just use the option presented. 

Approving now, thanks for the contribution.

**Pull request merged**
