### PR TITLE
QoL Changes

### PR DESCRIPTION
**Pull request by mgetzem**
Created a clear function to keep the CLI clean while performing analyst duties and switching between functions

### CODE REVIEW

**Comment by TheresAFewConors** [comment]
bca1c5b - changes suggested

c505d44 - approved


Please make appropriate changes to commit - it can then be merged when ready.

**Comment by mgetzem** [comment]
Sounds good, will make changes. For gathering info from multiple fields, we could save the results to an array and provide an option to output or export all, might be easier to read than it currently is in CLI

**Comment by TheresAFewConors** [comment]
Thanks very much, looking forward to the changes.

A batch export is something that would be extremely useful to add to the project, especially for building a case, (possibly an option to export to csv / xml). rather than scrolling back through the findings. 

If you want to implement something like that I would be more than willing to add it to the project.

**Comment by TheresAFewConors** [comment]
Just bumping to see if you are still interested in making changes / batch export to project?

**Comment by TheresAFewConors** [comment]
Closed due to inactivity

**Pull request closed without merging**
