### PR TITLE
Configuration of API keys split out to a separate file

### PR DESCRIPTION
**Pull request by naveci**
Creating the ability to have the config (API keys) in a separate file. This way, the keys (and possibly other future config) won't be overwritten by pulling a newer version of the software through git.

### CODE REVIEW

**Comment by naveci** [comment]
PR 2: 
Added text hashing function

PR 3:
Added Cisco password 7 decode ability to the script. This way, the user no longer has to enter their password in some third party website in order to get the original password.

Common use case for network engineers when looking at existing config and trying to figure out local accounts or Radius configuration.

**Comment by naveci** [comment]
Merge pull # 4 fixes [issue 32](https://github.com/TheresAFewConors/Sooty/issues/32)

**Comment by TheresAFewConors** [comment]
Thanks for the PR, the config file is a change that I've been meaning to make - I will take a look over the next few days and respond as soon as possible.

**Comment by naveci** [comment]
There is now a conflict caused by the imports, but is nothing serious. I've tested the method I've proposed on importing files and it works.
The difference in the proposal is that the filedialog is now imported as a part of tkinter. This means that in the code it should be referred to as tkinter.filedialog
See the [python docs](https://pythonbasics.org/tkinter_filedialog/) on this.

import tkinter
import tkinter.filedialog

Old:
from tkinter import *
from tkinter import filedialog


The reason why the old is not ideal is that it causes the program to import a lot of functions and classes that will never be used, thus slowing down the program. VsCode with pylint gave me 88 warnings on this line alone due to this.
The proposed change will prevent this from happening.

**Comment by TheresAFewConors** [comment]
Excellent fixes and improvements in this PR. Approved and merged. I'll get you added to the contributors list now.

Thanks very much for the work put in. Its an excellent addition.

**Pull request merged**
