### PR TITLE
Output to TxT file

### PR DESCRIPTION
**Pull request by nitin-techie**
The following feature has been added : 
1.) Output from reputation check for email, Ip, URL will be saved to a txt file automatically. The name of the txt file is same as the input (Ip, email, URL)

## Description ##
1.) Output from reputation check for email, Ip, URL will be saved to a txt file automatically. The name of the txt file is same as the input (Ip, email, URL)

## Does this fix a known existing bug under Issues? ##
#71 

## Type of Change ##
Please delete any options that **do not** apply here:
- [ ] New Feature

## Any further info related to the addition ##
Provide any additional details that seem relevant here if necessary, otherwise either delete or leave this section blank.

### CODE REVIEW

**Comment by nitin-techie** [comment]
@TheresAFewConors  -- This enhancement is complete. Kindly review.

**Review by TheresAFewConors — CHANGES_REQUESTED** [review]
appears to be functioning correctly, its a good QoL addition too. 

Could you also add the WhoIS output from the reputation checker to text file, and move the output files into their own directory - something like Sooty/Output/[date/time]/[1.1.1.1]? These last additions should make retrieving reports from previous events a little easier for continuing investigations. 

Thanks

**Comment by nitin-techie** [comment]
@TheresAFewConors  -- Yes, Sure 
I will make the changes and keep u posted

**Comment by nitin-techie** [comment]
@TheresAFewConors  -- the requested change is complete.
While commiting, pls be sure to add a folder 'output' in the repo as i have hardcoded that in the file path. 
The date and IP/URL is variable depending on input

**Review by TheresAFewConors — APPROVED** [review]
approved

**Pull request merged**
